### ISSUE TITLE
Pipeline overview shows wrong times and wrong color

### ISSUE THREAD

**Issue by galindro** [jenkinsci/pipeline-graph-view-plugin#362] opened 2024-03-12 12:13 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins version: 2.440.1
  pipeline-graph-view-plugin version: 230.vcd408a_1308dc
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

RHEL8

### Reproduction steps

Execute any pipeline with multiple steps within multiple parallel stages.

### Expected Results

The counter of previous steps shouldn't increment and the undone steps should be blue, not green.

### Actual Results

This weird behavior:

![output](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/4622097/ee09d512-94b4-4911-af0b-b9ca2978fb20)

**Comment by stuartrowe** [comment] 2024-03-12 22:54
@timbrown5 @timja I just recently fixed in-progress steps showing blue instead of green (https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/345). I'm now seeing this too after taking the latest version. I'm assuming https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/285 may have changed the status being returned for nodes in this situation? I'll try to debug this later tonight.

**Comment by stuartrowe** [comment] 2024-03-13 07:05
@timbrown5 [`NodeRelationship.java#L124`](https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/ecb8c5841335c42b0062bf35a885ea8e7f646f9c/src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationship.java#L124) is the cause of running step nodes being reported as complete. Removing this check and letting `StatusAndTiming.computeChunkStatus2` handle all cases  ([`NodeRelationship.java#L132`](https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/ecb8c5841335c42b0062bf35a885ea8e7f646f9c/src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationship.java#L132)) solves the issue for a simple repro pipeline:
```
stage("sleep") {
    sleep(60)
}
```
Unfortunately with that change alone there are a few test regressions that I need to dig into.

**Comment by timbrown5** [comment] 2024-03-13 07:50
Ahh, that was added to avoid cases where finished steps that were part of an unfinished block were reported as running (i.e. there was no BlockEndNode for the `after` parameter). 
If `stepAtomNodes should be excluded from this check, you might be able to simple do:
```
if (this.start != this.end && this.after == null && !isRunning(run)) {
```
(as for steps, relations have the start and end to the same StepAtomNode).
or:

```
if (this.end instanceof BlockEndNode && this.after == null && !isRunning(run)) {
```
*should* make this check only trigger for blocks.

My thinking (maybe wrong) is that if a Block has an end node, it should be finished (by definition?). The StatusAndTimingApi checks for an after node, which we can't assign until the parent block has finished. This causes problems for stages blocks with long running siblings, as it will be reported running until those siblings have finished.

**Comment by timbrown5** [comment] 2024-03-13 08:04
For the original bug, I think it's similar to the issue I found with the getting the status -if there is no after it is assumed to still be running.
https://github.com/jenkinsci/pipeline-graph-analysis-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/pipelinegraphanalysis/StatusAndTiming.java#L376
This could be a bug in how TreeScanner finds `after` nodes. Where step B follows step A in a block, step A's after should be step B - maybe this isn't the case.

I did consider assigning the `after` stage to  be the same as `end` in cases wee we cannot find `after`, but I think this could end with the step total time being set to 0 (as total time = `endTime-startTIme` - where `endTime` is likely the `after` start time and `after`==`end`==`start`).
https://github.com/jenkinsci/pipeline-graph-analysis-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/pipelinegraphanalysis/StatusAndTiming.java#L394

**Comment by timbrown5** [comment] 2024-03-13 08:12
Also, do you have a simple Pipeline to reproduce it?

**Comment by stuartrowe** [comment] 2024-03-13 09:09
> Also, do you have a simple Pipeline to reproduce it?

```
stage("sleep") {
    sleep(60)
}
```
The sleep step will appear to be completed even though it's still running.

**Comment by galindro** [comment] 2024-03-13 12:22
Please, test with parallel stages as well. I have identified another weird behavior that perhaps can be solved by a fix for this ticket: 

The stage `build:export:lib` got duplicated and one hsa marked as skipped. However, it should show only one stage called `build:export:lib` and it wasn't skipped.

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/4622097/0b3bed6f-a3ca-4fbe-b512-1d2f21073d66)

**Comment by galindro** [comment] 2024-03-13 12:25
Right after I wrote the previous message, it a 3rd `build:export:lib` stage was created and marked as skipped. It's totally random:

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/4622097/c33370d6-5fcb-46a1-9cc3-017d4d88d887)

**Comment by galindro** [comment] 2024-03-13 12:26
BTW, this isn't a nested parallel stages. Just a common parallel stages.

**Comment by galindro** [comment] 2024-03-13 12:42
but it doesn't fix the wrong color and timing, correct?

**Comment by timja** [comment] 2024-03-13 13:04
No thats just around skipped stages

**Comment by stuartrowe** [comment] 2024-03-14 06:32
@timbrown5 both suggested solutions had the same issue with the incorrect completed status of stages in a parallel block.
![Screen Recording 2024-03-13 at 11 20 43 PM](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/551572/9af91de7-ab9e-4e39-bf5c-6b9f28f49050)

Stage `Sleep B` changes to complete as soon as `Sleep A` actually completes. The `sleep` step within `Sleep B` will still run for another 15s.

Here's the pipeline I used:
```

stage("Build") {
    parallel([
        "A": { 
            stage("Sleep A") {
                sleep(15)
            }
            stage("Build A") {
                node {
                    sh("echo building A")
                }
            }
        },
        "B": {
            stage("Sleep B") {
                sleep(30)
            }
            stage("Build B") {
                node {
                    sh("echo building B")
                }
            }
            stage("Test B") {
                node {
                    sh("echo testing B")
                }
            }
        }
    ])
}
```

**Comment by stuartrowe** [comment] 2024-03-14 06:38
Relying on `StatusAndTiming.computeChunkStatus2` only introduces a another set of issues:

![Screen Recording 2024-03-13 at 11 34 49 PM](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/551572/f23d135e-5e98-4f9b-9126-3398e6ffbb88)

Stage `Sleep B` now completes (incorrectly) while `Sleep A` is still shown as in progress (incorrectly).

**Comment by timbrown5** [comment] 2024-03-14 10:08
> Relying on StatusAndTiming.computeChunkStatus2 only introduces a another set of issues:
The StatusAndTiming API make a lot of unhelpful assumptions (in our case at least) and isn't well documented - the help docs literally say to read the code to figure out how to use it :weary:. We have been advised not to use it (BlueOcean often prefers to generate it's own status/timing before replying on it):
https://issues.jenkins.io/browse/JENKINS-72771?focusedId=445879&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-445879

The check you mention is a hedge - if we didn't find an after node, but know the node/block isn't running, then calculate the status ourselves. We might be able to remove it if we are able to ensure we always get an after node when a step/block is finished (should be possible if the graph is well behaved in this instace - and it's often not).
I think, as you say, the error comes from:
```
if (this.after == null && !isRunning(run)) {
    return new NodeRunStatus(getFinishNodeStatus());
}
```
This should only fire when the node is not running, but obviously this step is running.

**Comment by timbrown5** [comment] 2024-03-14 10:32
@stuartrowe your issue should be fixed by #364 (if I've understood correctly). If you are able to check, that would be great :).

@galindro are you able to share a pipeline which reproduces the timing bug?
I think we are missing a condition here, but it would be good to check:
https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/main/src/main/java/io/jenkins/plugins/pipelinegraphview/treescanner/NodeRelationshipFinder.java#L91
(if we hit a step block inside a set of steps (e.g. a retry), then we might need to set the `after` node of the step before the block to the start of the step block).

**Comment by galindro** [comment] 2024-03-14 14:49
My pipeline is quite complex. It is based on a library that dynamically creates stages and then executes them in parallel. I can't share it due to IP (intelectual property).

However, I am sure you can simulate it with just some parallel stages like the one @stuartrowe used. The point here is that it seems to be something very random. The behaviors aren't the same. For every execution they flip.

**Comment by stuartrowe** [comment] 2024-03-14 19:22
@timbrown5 no, unfortunately the stage node is still being marked complete prematurely. Here's the same job running after checking out your branch. Note that the `sleep 30` step node is still in progress, but its parent stage `Sleep B` is marked complete as soon as its sibling stage `Sleep A` completes.

![Screen Recording 2024-03-14 at 12 13 57 PM](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/551572/59dce316-c540-4771-bd3d-64c1ff87b00e)

**Comment by galindro** [comment] 2024-03-14 20:06
This sounds to me a typical issue with memory sharing... Perhaps the same object is being used twice?

**Comment by stuartrowe** [comment] 2024-03-15 06:51
@timbrown5 I tested against your latest commit ([225b856](https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/364/commits/225b85692facc224c5479b0e5e349d972b33be11)) and the stage / step status are all correct now in my sample pipeline 🎉 

The only minor issue I see left is that the parallel branch `A` seems to inherit the timing info from branch `B` when `B` finally completes. Branch `A` should take roughly 15s because it contains a `sleep 15` step, while Branch `B` should take roughly 30s because it contains a `sleep 30` step. The timing info of all the stages within both branches is correct.

I appreciate all of your hard work on these issues! The console view is amazing now 👍 

<img width="638" alt="image" src="https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/551572/5d34b6f3-7ea3-486d-8134-858968b93aa2">

**Comment by timja** [comment] 2024-03-15 11:12
> (If you set up a logger for io.jenkins.plugins.pipelinegraphview.treescanner.* and level All that might get us further - assuming the Jenkins log listener supports wildcards 🤔 ).

Just do `io.jenkins.plugins.pipelinegraphview.treescanner` as the log recorder

**Comment by galindro** [comment] 2024-03-15 12:21
Yes sir!

**Comment by timbrown5** [comment] 2024-03-16 13:47
@galindro I have created #367 for your duplicate step issue. If we move the conversation to that but then we might be able to close this one.

**Comment by galindro** [comment] 2024-03-18 08:32
Just sent the logs there @timbrown5 / @timja

**Comment by timja** [comment] 2024-03-18 09:28
Closing as split into other issues

**Closed by timja** 2024-03-18 09:28 UTC
Labels: bug

**Comment by galindro** [comment] 2024-03-18 09:31
https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/367 - Duplicate stages

And what about the timing issue? Was it fixed by https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/364 ?

**Comment by timja** [comment] 2024-03-18 09:54
Yes

**Comment by timbrown5** [comment] 2024-03-18 12:40
Or tracked as #368
