### ISSUE TITLE
Console view should highlight status of stage/step

### ISSUE THREAD

**Issue by timbrown5** [jenkinsci/pipeline-graph-view-plugin#91] opened 2022-09-16 09:48 UTC
### What feature do you want to see added?

The items in the console view are all uniform. It would be nice to surface the status of the stage somehow.
I think could be done by setting the class of each TreeItem using the Stage/Step `state` property.

Then the CSS can be updated to style that group of items. Not sure how possible it would be, but might be nice to add the standard icons to each TreeItem, e.g.:
![Screenshot 2022-09-16 at 10 25 11 2](https://user-images.githubusercontent.com/4447764/190611596-f4548b72-a7f5-4244-be24-fcfef8acf6db.png)

**Comment by timja** [comment] 2022-09-16 09:59
Take a look at this branch:
https://github.com/timja/pipeline-graph-view-plugin/tree/add-more-componenets

**Comment by timbrown5** [comment] 2022-09-27 08:42
Duplicate of [29](https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/29)

**Comment by timja** [comment] 2022-09-27 10:26
Duplicate of https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/29

**Closed by timja** 2022-09-27 10:26 UTC
Labels: enhancement

**Comment by timbrown5** [comment] 2022-09-27 18:45
> Take a look at this branch: https://github.com/timja/pipeline-graph-view-plugin/tree/add-more-componenets
This is the sort of thing I was hoping for but, ideally, with colour (just to make it easier to see at a glance).

**Comment by timja** [comment] 2022-09-27 21:21
should be fine to add that but will probably do as an enhancement on top
