### ISSUE TITLE
Some skipped steps are wrongly displayed as in progress

### ISSUE THREAD

**Issue by lemeurherve** [jenkinsci/pipeline-graph-view-plugin#220] opened 2023-02-22 11:51 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.392
OS: Linux - 5.4.0-1098-azure
Java: 11.0.18 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
analysis-model-api:10.23.1
ansicolor:1.0.2
antisamy-markup-formatter:155.v795fb_8702324
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
authentication-tokens:1.4
aws-credentials:191.vcb_f183ce58b_9
aws-java-sdk-ec2:1.12.406-370.v8f993c987059
aws-java-sdk-minimal:1.12.406-370.v8f993c987059
azure-container-agents:253.vd2f5cd5c5040
azure-credentials:254.v64da_8176c83a
azure-sdk:118.v43f74dd9ca_dc
azure-vm-agents:822.v3a18fc3d2de1
basic-branch-build-strategies:71.vc1421f89888e
blueocean:1.27.1
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.1
blueocean-commons:1.27.1
blueocean-config:1.27.1
blueocean-core-js:1.27.1
blueocean-dashboard:1.27.1
blueocean-display-url:2.4.1
blueocean-events:1.27.1
blueocean-git-pipeline:1.27.1
blueocean-github-pipeline:1.27.1
blueocean-i18n:1.27.1
blueocean-jira:1.27.1
blueocean-jwt:1.27.1
blueocean-personalization:1.27.1
blueocean-pipeline-api-impl:1.27.1
blueocean-pipeline-editor:1.27.1
blueocean-pipeline-scm-api:1.27.1
blueocean-rest:1.27.1
blueocean-rest-impl:1.27.1
blueocean-web:1.27.1
bootstrap5-api:5.2.1-3
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-name-setter:2.2.0
buildtriggerbadge:251.vdf6ef853f3f5
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.8.1
cloud-stats:267.v577e3742c282
cloudbees-bitbucket-branch-source:796.v6cb_1559e1673
cloudbees-folder:6.800.v71307ca_b_986b
cloudbees-jenkins-advisor:326.v1821e6a_85e3f
cobertura:1.17
code-coverage-api:3.5.0
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-27.vb_fa_3896786a_7
config-file-provider:3.11.1
configuration-as-code:1569.vb_72405b_80249
copyartifact:686.v6fd37018d7c2
credentials:1214.v1de940103927
credentials-binding:523.vd859a_4b_122e6
dark-theme:302.vf069cb_e01486
data-tables-api:1.12.1-4
datadog:5.3.0
design-library:198.va_55cf2107e00
display-url-api:2.3.7
docker-commons:1.21
durable-task:504.vb10d1ae5ba2f
ec2:2.0.5
echarts-api:5.4.0-1
extended-read-permission:3.2
favorite:2.4.1
font-awesome-api:6.2.1-1
forensics-api:1.17.0
git:5.0.0
git-client:4.1.0
git-forensics:1.11.0
github:1.37.0
github-api:1.303-400.v35c2d8258028
github-autostatus:3.6.2
github-branch-source:1701.v00cc8184df93
github-checks:1.0.19
github-label-filter:1.0.0
groovy:453.vcdb_a_c5c99890
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.31
inline-pipeline:1.0.2
instance-identity:142.v04572ca_5b_265
ionicons-api:31.v4757b_6987003
jackson2-api:2.14.2-319.v37853346a_229
jacoco:3.3.2
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jenkins-design-language:1.27.1
jersey2-api:2.38-1
jira:3.9
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.16-2
job-dsl:1.81
jquery3-api:3.6.1-2
jsch:0.1.55.61.va_e9ee26616e7
junit:1177.v90374a_ef4d09
kubernetes:3883.v4d70a_a_a_df034
kubernetes-client-api:6.4.1-208.vfe09a_9362c2c
kubernetes-credentials:0.10.0
kubernetes-credentials-provider:1.209.v862c6e5fb_1ef
ldap:659.v8ca_b_a_fe79fa_d
lockable-resources:1123.v4002ee23c671
mailer:448.v5b_97805e3767
matrix-auth:3.1.6
matrix-project:785.v06b_7f47b_c631
metrics:4.2.13-420.vea_2f17932dd6
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
node-iterator-api:49.v58a_8b_35f8363
okhttp-api:4.10.0-125.v3593b_a_f8c97b_
pipeline-build-step:2.18.1
pipeline-github:2.8-138.d766e30bb08b
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-graph-view:154.v52138b_cb_557e
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-rest-api:2.31
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.31
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:2.20.0
popper2-api:2.11.6-2
prism-api:1.29.0-2
prometheus:2.1.1
pubsub-light:1.17
scm-api:631.v9143df5b_e4a_a
scm-filter-branch-pr:0.5.1
script-security:1229.v4880b_b_e905a_6
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
sse-gateway:1.26
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:305.v8f4381501156
sshd:3.275.v9e17c10f2571
structs:324.va_f5d6774f3a_d
support-core:1260.va_12d1e2d609a
theme-manager:1.6
timestamper:1.22
token-macro:321.vd7cc1f2a_52c8
toolenv:1.2
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
warnings-ng:9.23.1
windows-azure-storage:380.va3a027b784f4
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:1010.vf7a_b_98e847c1
workflow-cps:3618.v13db_a_21f0fcf
workflow-durable-task-step:1234.v019404b_3832a
workflow-job:1268.v6eb_e2ee1a_85a
workflow-multibranch:733.v109046189126
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

infra.ci.jenkins.io

### Reproduction steps

1. Merge a PR on https://github.com/jenkins-infra/kubernetes-management
2. Look at the main branch pipeline on infra.ci.jenkins.io (private instance, behind a VPN)

### Expected Results

Nothing shown for these skipped steps, like in BlueOcean:

![image](https://user-images.githubusercontent.com/91831478/220612057-dcf3856f-60a9-4aad-b95c-528f092540c1.png)

### Actual Results

Notice that some skipped "Diff on pull request" steps are shown as "in progress" (`...`):

![image](https://user-images.githubusercontent.com/91831478/220612125-e18616a7-6423-42a5-ad63-c5129aa4e03c.png)

**Comment by timja** [comment] 2023-02-22 12:14
Can you provide a sample pipeline as well please?

**Comment by lemeurherve** [comment] 2023-02-22 12:48
> This I assume?
[jenkins-infra/kubernetes-management@main/Jenkinsfile_k8s](https://github.com/jenkins-infra/kubernetes-management/blob/main/Jenkinsfile_k8s?rgh-link-date=2023-02-22T12%3A14%3A05Z)

Yes that one exactly! Not sure how difficult it would be to reproduce though.

**Comment by lemeurherve** [comment] 2023-10-08 00:46
I've reproduced it locally with the following test pipeline:

```
pipeline {
  agent any

  stages {
    stage('Hello') {
      steps {
        echo 'Hello World'
      }
    }
    stage('Kubernetes Management Tasks') {
      matrix {
        axes {
          axis {
            name 'K8S_CLUSTER'
            values 'cik8s', 'doks', 'doks-public', 'eks-public', 'privatek8s', 'publick8s'
          }
        } // axes
        stages {
          stage('Prepare Environment'){
            steps {
              echo 'Hello World'
            }
          }
          stage('Helmfile Lint'){
            steps {
              echo 'Hello World'
            }
          } // stage
          stage('Diff on Pull Request'){
            when {
              changeRequest()
            }
            steps {
              echo 'Hello World'
            }
          } // stage
          stage('Apply'){
            when {
              branch 'main'
            }
            steps {
              echo 'Hello World'
            }
          } // stage
        } // stages
      } // matrix
    } // stage 'stage('Kubernetes Management Tasks')
  }
}
```

<details><summary>Console logs where every "diff on pull request" & "apply" steps are "skipped due to when conditional":</summary>

```
Started by user unknown or anonymous
Replayed #4
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /Users/veve/j-infra/pipeline-graph-view-plugin/work/workspace/test
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Hello)
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Kubernetes Management Tasks)
[Pipeline] parallel
[Pipeline] { (Branch: Matrix - K8S_CLUSTER = 'cik8s')
[Pipeline] { (Branch: Matrix - K8S_CLUSTER = 'doks')
[Pipeline] { (Branch: Matrix - K8S_CLUSTER = 'doks-public')
[Pipeline] { (Branch: Matrix - K8S_CLUSTER = 'eks-public')
[Pipeline] { (Branch: Matrix - K8S_CLUSTER = 'privatek8s')
[Pipeline] { (Branch: Matrix - K8S_CLUSTER = 'publick8s')
[Pipeline] stage
[Pipeline] { (Matrix - K8S_CLUSTER = 'cik8s')
[Pipeline] stage
[Pipeline] { (Matrix - K8S_CLUSTER = 'doks')
[Pipeline] stage
[Pipeline] { (Matrix - K8S_CLUSTER = 'doks-public')
[Pipeline] stage
[Pipeline] { (Matrix - K8S_CLUSTER = 'eks-public')
[Pipeline] stage
[Pipeline] { (Matrix - K8S_CLUSTER = 'privatek8s')
[Pipeline] stage
[Pipeline] { (Matrix - K8S_CLUSTER = 'publick8s')
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Prepare Environment)
[Pipeline] stage
[Pipeline] { (Prepare Environment)
[Pipeline] stage
[Pipeline] { (Prepare Environment)
[Pipeline] stage
[Pipeline] { (Prepare Environment)
[Pipeline] stage
[Pipeline] { (Prepare Environment)
[Pipeline] stage
[Pipeline] { (Prepare Environment)
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Helmfile Lint)
[Pipeline] stage
[Pipeline] { (Helmfile Lint)
[Pipeline] stage
[Pipeline] { (Helmfile Lint)
[Pipeline] stage
[Pipeline] { (Helmfile Lint)
[Pipeline] stage
[Pipeline] { (Helmfile Lint)
[Pipeline] stage
[Pipeline] { (Helmfile Lint)
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] echo
Hello World
[Pipeline] }
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Diff on Pull Request)
[Pipeline] stage
[Pipeline] { (Diff on Pull Request)
[Pipeline] stage
[Pipeline] { (Diff on Pull Request)
[Pipeline] stage
[Pipeline] { (Diff on Pull Request)
[Pipeline] stage
[Pipeline] { (Diff on Pull Request)
[Pipeline] stage
[Pipeline] { (Diff on Pull Request)
Stage "Diff on Pull Request" skipped due to when conditional
[Pipeline] }
Stage "Diff on Pull Request" skipped due to when conditional
[Pipeline] }
Stage "Diff on Pull Request" skipped due to when conditional
[Pipeline] }
Stage "Diff on Pull Request" skipped due to when conditional
[Pipeline] }
Stage "Diff on Pull Request" skipped due to when conditional
[Pipeline] }
Stage "Diff on Pull Request" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Apply)
[Pipeline] stage
[Pipeline] { (Apply)
[Pipeline] stage
[Pipeline] { (Apply)
[Pipeline] stage
[Pipeline] { (Apply)
[Pipeline] stage
[Pipeline] { (Apply)
[Pipeline] stage
[Pipeline] { (Apply)
Stage "Apply" skipped due to when conditional
[Pipeline] }
Stage "Apply" skipped due to when conditional
[Pipeline] }
Stage "Apply" skipped due to when conditional
[Pipeline] }
Stage "Apply" skipped due to when conditional
[Pipeline] }
Stage "Apply" skipped due to when conditional
[Pipeline] }
Stage "Apply" skipped due to when conditional
[Pipeline] }
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] // withEnv
[Pipeline] // withEnv
[Pipeline] // withEnv
[Pipeline] // withEnv
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] // stage
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] }
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

```

</details>

Screenshot of the Pipeline Overview showing the first set of "diff on pull request" & "apply" steps not skipped:

<img width="786" alt="image" src="https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/91831478/3c305d66-bac8-47f4-8983-696b1a9c6f79">

**Comment by timja** [comment] 2024-03-09 16:55
Looking at blueocean I suspect its this code:
https://github.com/jenkinsci/blueocean-plugin/blob/c6407e6e25c671eb29fec420a1e2d8f92137a079/blueocean-pipeline-api-impl/src/main/java/io/jenkins/blueocean/rest/impl/pipeline/NodeRunStatus.java#L52-L53

Where it defaults to not built.
The existing code doesn't work because it was relying on an action `TagsAction` being attached to the flownode but that doesn't seem to reliably be there:
https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/285?notification_referrer_id=NT_kwDOAUNoHrM2ODY1MzY0NDU1OjIxMTk0Nzgy&notifications_query=is%3Aunread#issuecomment-1986230291

cc @timbrown5

**Comment by timja** [comment] 2024-03-09 19:21
I suspect this is a bug in declarative pipeline, somewhere around:
https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/76afff0a26188ad6ced215e4663cd2115c003a74/pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy#L311C17-L328

The whole `TagsAction` appears to have been added for blue ocean but I don't think they ever ended up using it...

So potentially it never worked properly.

If I look in `flowNodeStore.xml` there are only 2 `TagsAction`, one for a `Diff on pull request stage` and one for an `Apply` stage.

So I wonder if its keyed by the stage name and only works once if the name is the same.

**Comment by timja** [comment] 2024-03-09 19:27
Likely this: https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/76afff0a26188ad6ced215e4663cd2115c003a74/pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy#L240

**Comment by timja** [comment] 2024-03-09 19:29
FWIW the behaviour has changed at some point to be accurate based on the data provided:

<img width="779" alt="image" src="https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/21194782/3aa3bd30-5e66-4346-bbe9-8ae98db11ff6">

**Comment by timja** [comment] 2024-03-09 19:35
Raised https://issues.jenkins.io/browse/JENKINS-72841

**Comment by timja** [comment] 2024-03-10 23:02
Created https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/698

**Comment by mathieugouin** [comment] 2024-03-22 00:24
I have a very simple Jenkinsfile in #326.  It was confirmed that my issue was a duplicate of this one, but still it has a detailed "testcase" pipeline to help confirm when the fix is available if it works.
Thanks!

**Comment by lemeurherve** [comment] 2024-03-24 14:48
@timja FWIW I've got another strange graph with a "prepare" and 2 of 3 "deploy" stages wrongly shown as "done" while all of them have been skipped:

<img width="692" alt="image" src="https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/91831478/9f5ab164-7e4c-4fa8-892e-663f3c446e90">

https://ci.jenkins.io/job/Packaging/job/docker-ssh-agent/job/PR-289/69/

**Comment by timja** [comment] 2024-03-24 15:20
You could try with this: https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/700

I've triggered a build to get an incremental.

**Comment by timja** [comment] 2024-04-11 06:52
This should be fixed now by updating the declarative pipeline version

**Comment by mathieugouin** [comment] 2024-04-17 15:04
@timja I have a similar problem, even after the fix.  Here is my test pipeline:

```
pipeline {
    agent none
    stages {
        stage('Matrix') {
            matrix {
                agent any
                axes {
                    axis {
                        name 'JK_BUILD_CONFIG' // JK = JenKins...
                        values  'A1', 'A2', 'B1', 'B2'
                    }
                }
                stages {
                    stage('Stage No Condition 1') {
                        steps {
                            echo "In Stage No Condition 1 for config: ${JK_BUILD_CONFIG}"
                        }
                    }
                    stage('Stage Condition A') {
                        when {
                            expression { return env.JK_BUILD_CONFIG =~ /A/ }
                        }
                        steps {
                            echo "Stage Condition A for config: ${JK_BUILD_CONFIG}"
                        }
                    }
                    stage('Stage No Condition 2') {
                        steps {
                            echo "In Stage No Condition 2 for config: ${JK_BUILD_CONFIG}"
                        }
                    }
                    stage('Stage Condition B') {
                        when {
                            expression { return env.JK_BUILD_CONFIG =~ /B/ }
                        }
                        steps {
                            echo "Stage Condition B for config: ${JK_BUILD_CONFIG}"
                        }
                    }
                }
            }
        }
    }
}
```

Here is the output:

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/11562302/6bb5a7d7-473b-4f7c-ac8f-29079b5a77eb)

As you can see, the 2nd line is the matrix value `A2`.  Condition `B` should not be marked as green.

Let me know if you need more info.

Thanks

**Comment by mathieugouin** [comment] 2024-04-18 15:42
Pipeline: Declarative (pipeline-model-definition): 2.2198.v41dd8ef6dd56

**Comment by timja** [comment] 2024-04-18 20:37
The pipeline seems to work fine for me?

<img width="700" alt="image" src="https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/21194782/d7c3cb1e-724e-426b-8184-7069d85848c9">

Can you ensure all plugins are to update, that you are using at least Jenkins version 2.440.1 and have restarted Jenkins since updating plugins?

If you are and can still reproduce it can you file a new issue, as that will contain full environment information for debugging further

**Closed by timja** 2024-04-18 20:37 UTC
Labels: bug

**Comment by mathieugouin** [comment] 2024-04-19 13:18
@timja After full update, it works same as you.  Maybe there was other dependencies.  Thanks!
