### ISSUE TITLE
No vertical scroll bar on Pipeline Console when there are lots of steps

### ISSUE THREAD

**Issue by bandi13** [jenkinsci/pipeline-graph-view-plugin#338] opened 2024-02-02 19:10 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller - Ubuntu 22.04

### Reproduction steps

To reproduce, simply create a job with several steps and a few stages like so:
![2024-02-02-092117_1837x800_scrot](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/5672741/4d6cd43f-02d4-41bf-96f6-a0c0fd2bef93)

The problem is there is no way to scroll further down on the left column. There used to be a scroll bar, but it no longer is there. As you can see, there is another test below `PRB_dtls.txt_21`, but you can't get there.

### Expected Results

I expect a scroll bar on the left list box.

### Actual Results

Missing scroll bar on long lists.

### Anything else?

I'm using Jenkins 2.426.3 with the Pipeline Graph View Plugin Version 215.vc0ea_557e4d6f. I've tried rolling back to the previous version (205.vb_8e3a_b_51f12e), but that wouldn't render the page.

**Comment by timja** [comment] 2024-02-02 22:11
Duplicate of https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/325

The plugin baseline is at the next LTS as it's depending on a new feature.
Next LTS is released on 7th of February

**Closed by timja** 2024-02-02 22:11 UTC
Labels: bug
