### ISSUE TITLE
Possibility to download an image of the graph

### ISSUE THREAD

**Issue by Jonakss** [jenkinsci/pipeline-graph-view-plugin#60] opened 2022-03-25 17:57 UTC
### What feature do you want to see added?

It would be useful for notifications, have the possibility to get a png and/or svg of the graph from the .../pipeline-graph/png
When we make the GET request it returns the image directly.

For example: 
```http://jenkins.url/job/<JobName>/job/<ProjectName>/51/pipeline-graph/png```

**Comment by mikedld** [comment] 2022-09-06 05:09
Related to #17.

**Comment by timja** [comment] 2022-09-10 21:29
Duplicate of https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/17

**Closed by timja** 2022-09-10 21:29 UTC
Labels: enhancement
