### ISSUE TITLE
Wrong pipeline graph and console view display of matrix with conditional stage

### ISSUE THREAD

**Issue by mathieugouin** [jenkinsci/pipeline-graph-view-plugin#326] opened 2024-01-23 20:18 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.426.2
OS: Windows 10 - 10.0
Java: 21.0.1 - Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM)
---
analysis-model-api:11.15.0
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
bootstrap5-api:5.3.2-3
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1144.v1425d1c3d5a_7
build-monitor-plugin:1.14-826.vb_a_c11536174d
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloudbees-folder:6.858.v898218f3609d
command-launcher:107.v773860566e2e
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-95.v22a_d30ee5d36
credentials:1311.vcf0a_900b_37c2
credentials-binding:657.v2b_19db_7d6e6d
data-tables-api:1.13.8-2
display-url-api:2.200.vb_9327d658781
durable-task:543.v262f6a_803410
echarts-api:5.4.3-2
email-ext:2.104
font-awesome-api:6.5.1-2
forensics-api:2.3.0
git:5.2.1
git-client:4.6.0
gson-api:2.10.1-15.v0d99f670e0a_7
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.16.1-373.ve709c6871598
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
joda-time-api:2.12.6-21.vca_fd74418fb_7
jquery3-api:3.7.1-1
json-path-api:2.8.0-21.v8b_7dc8b_1037b_
junit:1256.v002534a_5f33e
mailer:463.vedf8358e006b_
mapdb-api:1.0.9-28.vf251ce40855d
matrix-project:822.v01b_8c85d16d2
metrics:4.2.18-442.v02e107157925
mina-sshd-api-common:2.12.0-90.v9f7fb_9fa_3d3b_
mina-sshd-api-core:2.12.0-90.v9f7fb_9fa_3d3b_
monitoring:1.95.0
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-graph-view:214.v6e2833d3fea_9
pipeline-groovy-lib:700.v0e341fa_57d53
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2175.v76a_fff0a_2618
pipeline-model-definition:2.2175.v76a_fff0a_2618
pipeline-model-extensions:2.2175.v76a_fff0a_2618
pipeline-rest-api:2.34
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2175.v76a_fff0a_2618
pipeline-stage-view:2.34
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.8.0
prism-api:1.29.0-10
resource-disposer:0.23
scm-api:683.vb_16722fb_b_80b_
script-security:1313.v7a_6067dc7087
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-credentials:308.ve4497b_ccd8f4
sshd:3.322.v159e91f6a_550
structs:337.v1b_04ea_4df7c8
subversion:2.17.3
timestamper:1.26
token-macro:400.v35420b_922dcb_
trilead-api:2.133.vfb_8a_7b_9c5dd1
variant:60.v7290fc0eb_b_cd
warnings-ng:10.7.0
workflow-aggregator:596.v8c21c963d92d
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3837.v305192405b_c0
workflow-durable-task-step:1313.vcb_970b_d2a_fb_3
workflow-job:1385.vb_58b_86ea_fff1
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:415.v434365564324
workflow-step-api:657.v03b_e8115821b_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

* Controller: WIN 10
* No agent, only a single controller

### Reproduction steps

1. From the Jenkins Dashboard, click "New Item"
2. Give a name (eg: TestPipeline3)
3. Select "Pipeline"
4. Click "OK"
5. Scroll down to Pipeline section
6. Select "Pipeline Script"
7. Paste the following in the textbox as the pipeline:
```groovy
pipeline {
    agent none
    stages {
        stage('Matrix') {
            matrix
            {
                agent any
                axes {
                    axis {
                        name 'JK_BUILD_CONFIG' // JK = JenKins...
                        values  'A1', 'A2', 'B1', 'B2'
                    }
                }
                stages {
                    stage('Stage No Condition 1') {
                        steps {
                            echo "In Stage No Condition 1 for config: ${JK_BUILD_CONFIG}"
                        }
                    }
                    stage('Stage Condition A') {
                        when {
                            expression { return env.JK_BUILD_CONFIG =~ /A/ }
                        }
                        steps {
                            echo "Stage Condition A for config: ${JK_BUILD_CONFIG}"
                        }
                    }
                    stage('Stage Condition B')
                    {
                        when {
                            expression { return env.JK_BUILD_CONFIG =~ /B/ }
                        }
                        steps {
                            echo "Stage Condition B for config: ${JK_BUILD_CONFIG}"
                        }
                    }
                    stage('Stage No Condition 2') {
                        steps {
                            echo "In Stage No Condition 2 for config: ${JK_BUILD_CONFIG}"
                        }
                    }
                }
            }
        }
    }
}
```
8. Click on "Save"
9. Click on "Build Now", wait for the build to complete
10. Under Permalinks, click on "Last Build"
11. Click on "Pipeline Overview"

### Expected Results

On the first horizontal graph line representing the `A1` config, the `Stage Condition A` should be green and the `Stage Condition B` should be skipped.

### Actual Results

On the first horizontal graph line representing the `A1` config, both the `Stage Condition A` and the `Stage Condition B` are represented by an empty gray circles.

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/11562302/f508ba15-2b2f-431b-be7b-bb954575b31a)

### Anything else?

In the "Pipeline Console" view, the `Stage 'Matrix - JK_BUILD_CONFIG = 'A1''` also displays `Stage Condition A` and `Stage Condition B` as empty gray circles.

You can confirm that the axis `A1` was properly executed by looking at the regular "Console Output".

### Are you interested in contributing a fix?

Maybe, but I have no experience in developping Jenkins plugins...

**Comment by timja** [comment] 2024-03-07 22:03
Likely duplicate of https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/220

**Comment by timja** [comment] 2024-03-10 20:58
Confirmed duplicate of https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/220

The behaviour has likely changed recently in such that the first skipped stage will show skipped.

Its a bug in declarative pipeline where it only marks the first stage as skipped: https://issues.jenkins.io/browse/JENKINS-72841

**Closed by timja** 2024-03-10 20:58 UTC
Labels: bug
